### ISSUE TITLE
安装后启动websocket.io-spec报错

### ISSUE THREAD

**Issue by rainwalkerhu** [Treri/fis3-typescript-vue-hackernews-2.0#1]
/Users/rain/fis3-typescript-vue-hackernews-2.0/node_modules/websocket.io-spec/lib/socket.js:49
Socket.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined

**Comment by ik0r** [comment]
fis3 目前不支持 node 7, 请使用 node 6
